/**
 * Shared `fast-check` arbitraries for the `@cosyte/dicom` property-test layer.
 *
 * Everything here is **synthetic** — generated byte streams and structural
 * shapes, never real PHI (D-38: the repo ships zero curated `.dcm` files).
 *
 * Three families of generators live here:
 *
 * 1. **Spec-valid models** ({@link wellFormedModel}) — a structural
 *    description (`DicomModel`) the {@link buildDicom} test-helper encoder can
 *    emit and `parseDicom` can re-read with structural fidelity. These drive
 *    the round-trip invariant. They deliberately AVOID the documented
 *    round-trip traps (Explicit-BE numeric byte-swap, odd-length padding,
 *    File Meta group-length recovery) so a structural-equality failure means a
 *    real bug, not a known lossy transform. See {@link encodeModel} for the
 *    canonical-form claim.
 *
 * 2. **Malformed-but-recoverable streams** ({@link recoverableInput}) — valid
 *    Part 10 buffers carrying TOL-03 deviations (missing preamble, group-length
 *    mismatch, odd-length value, retired group-length, non-zero reserved bytes,
 *    undefined-length under Explicit VR, empty SQ item) that the parser must
 *    recover into warnings, plus a handful that legitimately throw a Tier-3
 *    fatal. Drives the lenient invariant.
 *
 * 3. **Hostile bytes** ({@link arbitraryBytes}, {@link truncatedValidFile}) —
 *    arbitrary random buffers and random truncations of well-formed files. The
 *    parser must never throw an unexpected error, hang, or OOM on these; only
 *    sanctioned `DicomParseError` fatals. Drives the fuzz invariant.
 *
 * The format-specific knowledge stays here in the parser; the generic invariant
 * runners come from `@cosyte/test-utils`.
 *
 * @module
 */

import { Buffer } from "node:buffer";

import fc from "fast-check";

import type { Tag, VR } from "../../src/dictionary/types.js";
import {
  buildDicom,
  type BuildDicomElement,
  type BuildDicomOptions,
} from "../helpers/build-dicom.js";

// ---------------------------------------------------------------------------
// Transfer-syntax UIDs (the four v1 syntaxes dicom supports).
// ---------------------------------------------------------------------------

/** Implicit VR Little Endian. */
export const TS_IMPLICIT_LE = "1.2.840.10008.1.2";
/** Explicit VR Little Endian. */
export const TS_EXPLICIT_LE = "1.2.840.10008.1.2.1";
/** Explicit VR Big Endian (retired, still in the v1 set). */
export const TS_EXPLICIT_BE = "1.2.840.10008.1.2.2";
/** Deflated Explicit VR Little Endian. */
export const TS_DEFLATED_LE = "1.2.840.10008.1.2.1.99";

/** All four v1 transfer syntaxes. */
export const ALL_V1_TS = [TS_IMPLICIT_LE, TS_EXPLICIT_LE, TS_EXPLICIT_BE, TS_DEFLATED_LE] as const;

/**
 * The round-trip-safe transfer syntaxes. Explicit-BE is deliberately EXCLUDED
 * from round-trip generation: the encoder byte-swaps numeric VR values to BE on
 * emit while the parser stores `rawBytes` BE-ordered verbatim, so a value fed in
 * as LE-native would re-project as its byte-swapped self — a known, sanctioned
 * lossy transform, not a fidelity bug. Explicit-BE is still exercised by the
 * lenient + fuzz invariants. Deflated-LE round-trips losslessly (the dataset is
 * Explicit-LE under the deflate stream) so it stays in.
 */
const ROUND_TRIP_TS = [TS_IMPLICIT_LE, TS_EXPLICIT_LE, TS_DEFLATED_LE] as const;

// ---------------------------------------------------------------------------
// Spec-valid model + canonical encoder (round-trip invariant).
// ---------------------------------------------------------------------------

/**
 * A single dataset element in a {@link DicomModel}: an 8-hex tag, a VR, and the
 * value bytes as the PARSER will store them (LE / native order — the encoder's
 * call-site convention; see {@link BuildDicomElement}). `valueHex` is the
 * lowercase hex of those bytes, so the projection is a plain comparable string.
 */
export interface ModelElement {
  readonly tag: Tag;
  readonly vr: VR;
  /** Lowercase space-free hex of the value bytes (even length, as stored). */
  readonly valueHex: string;
}

/**
 * A structural, comparable description of a well-formed DICOM dataset. This is
 * the `T` that flows arbitrary → serialize → parse → equals in the round-trip
 * runner. `elements` is keyed by tag so insertion order does not perturb
 * equality (the parser stores elements in a `Map` keyed by tag).
 */
export interface DicomModel {
  readonly transferSyntax: string;
  /** Tag → element, deduplicated by tag (last write wins, mirroring the parser map). */
  readonly elements: Readonly<Record<string, ModelElement>>;
}

/**
 * Tag → canonical PS3.6 dictionary VR. Each element the round-trip generator
 * emits uses the VR the data dictionary lists for its tag. This is the key to
 * honest round-tripping across encodings:
 *
 *  - Under **Implicit VR LE** there is no on-wire VR, so the parser resolves the
 *    VR from this exact dictionary — the model's VR must equal it or the
 *    re-projection's VR diverges.
 *  - Under **Explicit VR LE** the same VR is written on-wire and trusted, and
 *    because it matches the dictionary, NO `DICOM_VR_MISMATCH` warning fires —
 *    the generator stays spec-clean (zero warnings), so a round-trip failure
 *    means a real fidelity bug, not a known lossy transform.
 *
 * Deliberately excludes `(gggg,0000)` group-length tags, `(0002,xxxx)` File Meta
 * tags, and `(7FE0,0010)` PixelData — each has a dedicated warning path the
 * lenient generator covers.
 */
const TAG_VR: Readonly<Record<Tag, VR>> = {
  "00080018": "UI", // SOPInstanceUID
  "00080060": "CS", // Modality
  "00080020": "DA", // StudyDate
  "00080030": "TM", // StudyTime
  "00100010": "PN", // PatientName
  "00100020": "LO", // PatientID
  "00100040": "CS", // PatientSex
  "0020000D": "UI", // StudyInstanceUID
  "0020000E": "UI", // SeriesInstanceUID
  "00280010": "US", // Rows
  "00280011": "US", // Columns
  "00181030": "LO", // ProtocolName
};

/** ASCII text VRs whose values are printable, space-padded to even length. */
const TEXT_VRS: ReadonlySet<VR> = new Set<VR>(["PN", "LO", "SH", "UI", "CS", "DA", "TM"]);

/**
 * Printable ASCII for text values — letters, digits, and a few delimiter-free
 * punctuation marks. Excludes backslash (the DICOM VM separator) and control
 * bytes so a single-valued element stays single-valued and the value never
 * collides with structural markers.
 */
const TEXT_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .-^";

/** A non-empty printable ASCII value, padded with a trailing space to even length. */
function textValueBytes(): fc.Arbitrary<Buffer> {
  return fc
    .stringOf(fc.constantFrom(...TEXT_ALPHABET.split("")), { minLength: 1, maxLength: 14 })
    .map((s) => {
      const buf = Buffer.from(s, "ascii");
      return buf.length % 2 === 0 ? buf : Buffer.concat([buf, Buffer.from([0x20])]);
    });
}

/** Exactly two bytes — a single `US` (Unsigned Short) value, stored verbatim under LE. */
function usValueBytes(): fc.Arbitrary<Buffer> {
  return fc.integer({ min: 0, max: 0xffff }).map((n) => {
    const buf = Buffer.alloc(2);
    buf.writeUInt16LE(n, 0);
    return buf;
  });
}

/** One spec-valid element model: a real tag + its dictionary VR + a valid value. */
function modelElementArb(): fc.Arbitrary<ModelElement> {
  return fc.constantFrom<Tag[]>(...Object.keys(TAG_VR)).chain((tag) => {
    const vr = TAG_VR[tag];
    if (vr === undefined) throw new Error(`modelElementArb: no VR for tag ${tag}`);
    const valueArb = TEXT_VRS.has(vr) ? textValueBytes() : usValueBytes();
    return valueArb.map((value) => ({ tag, vr, valueHex: value.toString("hex") }));
  });
}

/**
 * The round-trip arbitrary: a well-formed {@link DicomModel}. Elements are keyed
 * by tag (the parser stores them in a tag-keyed `Map`), so duplicate tags
 * collapse to one — matching parser semantics and keeping round-trip count
 * parity. Optionally includes one empty defined-length SQ element to exercise the
 * The model is fully self-describing: {@link encodeModel} re-encodes it
 * deterministically from `transferSyntax` + `elements` alone, so both the
 * original and any re-projected model serialize identically (the idempotency
 * half of the invariant).
 *
 * Round-trip scope is **primitive (leaf) elements only**. SQ is deliberately
 * excluded: an empty SQ's stored `rawBytes` differs by encoding (0 bytes under
 * Implicit VR LE vs the 12-byte header region under Explicit VR LE), and the SQ
 * value is not decoded into structured items until Phase 3 — so `rawBytes` is an
 * internal representation, not a clean structural-fidelity target yet. SQ
 * structure is exercised by the lenient + fuzz invariants and the existing
 * integration suite. When Phase 3 lands decoded SQ items, extend this generator
 * to round-trip them.
 */
export function wellFormedModel(): fc.Arbitrary<DicomModel> {
  return fc
    .record({
      transferSyntax: fc.constantFrom<string[]>(...ROUND_TRIP_TS),
      elements: fc.array(modelElementArb(), { minLength: 0, maxLength: 6 }),
    })
    .map(({ transferSyntax, elements }) => {
      const map: Record<string, ModelElement> = {};
      for (const el of elements) map[el.tag] = el; // last write wins (parser Map semantics)
      return { transferSyntax, elements: map };
    });
}

/**
 * Encode a {@link DicomModel} to its on-the-wire bytes, returned as a **latin1
 * string** (a lossless 1:1 byte↔code-unit mapping) so it satisfies the
 * `serialize: (T) => string` shape the round-trip runner requires while carrying
 * raw bytes faithfully. `parse` reverses this with `Buffer.from(str, "latin1")`.
 *
 * The encoding is canonical: elements are emitted in ascending tag order
 * (matching how the projection compares) so the function is a pure deterministic
 * function of the model. Re-encoding a re-projected model therefore yields
 * byte-identical output — the idempotency half of the round-trip invariant.
 */
export function encodeModel(model: DicomModel): string {
  const tags = Object.keys(model.elements).sort();
  const buildElements: BuildDicomElement[] = tags.map((tag) => {
    const el = model.elements[tag];
    if (el === undefined) throw new Error(`encodeModel: missing element for tag ${tag}`);
    return { tag: el.tag, vr: el.vr, value: Buffer.from(el.valueHex, "hex") };
  });
  return buildDicom({ transferSyntax: model.transferSyntax, elements: buildElements }).toString(
    "latin1",
  );
}

/** The byte form of a round-trip wire string. */
export function wireToBuffer(wire: string): Buffer {
  return Buffer.from(wire, "latin1");
}

/**
 * Test-only structural view of `Dataset._elements` — Phase 2 keeps the element
 * map `protected`; the public navigation API (`get` / `getAll`) lands in
 * Phase 3. Mirrors the `elementsOf` accessor used across the existing
 * integration + unit tests. Typed via a structural interface so no `any` is
 * needed.
 */
interface DatasetElementsView {
  readonly _elements: ReadonlyMap<
    string,
    { readonly tag: Tag; readonly vr: VR; readonly rawBytes: Buffer }
  >;
}

/**
 * Project a parsed `Dataset` (passed as `unknown` to avoid importing the class
 * into the arbitraries module) back into the comparable {@link DicomModel}
 * shape, reading the protected `_elements` map. `transferSyntax` comes from
 * `fileMeta.transferSyntaxUID`. This is the `parse`-side reprojection the
 * round-trip runner's `equals` compares against the generated model.
 */
export function projectDataset(ds: unknown): DicomModel {
  const view = ds as DatasetElementsView & { readonly fileMeta?: { transferSyntaxUID: string } };
  const elements: Record<string, ModelElement> = {};
  for (const [tag, el] of view._elements) {
    elements[tag] = { tag: el.tag, vr: el.vr, valueHex: el.rawBytes.toString("hex") };
  }
  return {
    transferSyntax: view.fileMeta?.transferSyntaxUID ?? "",
    elements,
  };
}

// ---------------------------------------------------------------------------
// Malformed-but-recoverable streams (lenient invariant).
// ---------------------------------------------------------------------------

/** A minimal spec-valid element used as filler inside recoverable fixtures. */
const FILLER_ELEMENT: BuildDicomElement = {
  tag: "00100010",
  vr: "PN",
  value: Buffer.from("DOE^JANE", "ascii"),
};

/**
 * Build a well-formed buffer carrying exactly ONE recoverable TOL-03 deviation,
 * chosen by `kind`. Each kind maps to a specific `WARNING_CODES` entry the
 * parser must emit (rather than throw). The transfer syntax varies to exercise
 * the deviation under multiple encodings.
 */
function recoverableFixture(): fc.Arbitrary<Buffer> {
  const leTs = fc.constantFrom<string[]>(TS_IMPLICIT_LE, TS_EXPLICIT_LE);

  // DICOM_MISSING_PREAMBLE — bare File Meta at offset 0.
  const missingPreamble = leTs.map((ts) =>
    buildDicom({ transferSyntax: ts, elements: [FILLER_ELEMENT], skipPreamble: true }),
  );

  // DICOM_FILE_META_GROUP_LENGTH_MISMATCH — under-reported group length.
  const groupLenMismatch = leTs.map((ts) =>
    buildDicom({
      transferSyntax: ts,
      elements: [FILLER_ELEMENT],
      fileMetaGroupLength: "wrong",
    }),
  );

  // DICOM_FILE_META_GROUP_LENGTH_MISSING — omit (0002,0000) entirely.
  const groupLenMissing = leTs.map((ts) =>
    buildDicom({
      transferSyntax: ts,
      elements: [FILLER_ELEMENT],
      fileMetaGroupLength: "omit",
    }),
  );

  // DICOM_ODD_LENGTH_VALUE_PADDED — an odd-length value (Explicit-LE so the
  // header carries the declared odd length on-wire).
  const oddLength = fc.constant(
    buildDicom({
      transferSyntax: TS_EXPLICIT_LE,
      elements: [{ tag: "00100020", vr: "LO", value: Buffer.from("ODD", "ascii") }],
    }),
  );

  // DICOM_GROUP_LENGTH_IN_DATASET — a retired (gggg,0000) element in the dataset.
  const groupLengthInDataset = leTs.map((ts) =>
    buildDicom({
      transferSyntax: ts,
      elements: [
        { tag: "00080000", vr: "UL", value: Buffer.from([0x04, 0x00, 0x00, 0x00]) },
        FILLER_ELEMENT,
      ],
    }),
  );

  // DICOM_UNDEFINED_LENGTH_IN_EXPLICIT_VR — SQ with undefined length under
  // Explicit-LE (legal but flagged).
  const undefinedLenExplicit = fc.constant(
    buildDicom({
      transferSyntax: TS_EXPLICIT_LE,
      elements: [{ tag: "0040A730", undefinedLength: true, items: [{ elements: [] }] }],
    }),
  );

  // DICOM_EMPTY_ITEM_IN_SEQUENCE — a zero-length item inside an SQ.
  const emptyItem = fc.constant(
    buildDicom({
      transferSyntax: TS_EXPLICIT_LE,
      elements: [{ tag: "0040A730", undefinedLength: true, items: [{ elements: [] }] }],
    }),
  );

  // DICOM_NONZERO_RESERVED_BYTES — hand-craft an Explicit-LE long-form header
  // with non-zero reserved bytes between VR and length.
  const nonzeroReserved = fc.constant(buildNonzeroReservedFixture());

  // Trailing junk after a valid dataset — exercises the post-dataset tolerance
  // path (may or may not warn; never throws).
  const trailingJunk = leTs.chain((ts) =>
    fc.uint8Array({ minLength: 1, maxLength: 16 }).map((bytes) =>
      buildDicom({
        transferSyntax: ts,
        elements: [FILLER_ELEMENT],
        trailingBytes: Buffer.from(bytes),
      }),
    ),
  );

  return fc.oneof(
    missingPreamble,
    groupLenMismatch,
    groupLenMissing,
    oddLength,
    groupLengthInDataset,
    undefinedLenExplicit,
    emptyItem,
    nonzeroReserved,
    trailingJunk,
  );
}

/**
 * Hand-build an Explicit-LE Part 10 buffer whose single dataset element has a
 * long-form header with NON-ZERO reserved bytes (the 2 bytes between VR and the
 * 4-byte length). The parser tolerates this and emits
 * `DICOM_NONZERO_RESERVED_BYTES`. `buildDicom` always writes zero reserved
 * bytes, so this case is constructed by hand.
 */
function buildNonzeroReservedFixture(): Buffer {
  // Start from a valid OB element (long-form), then poke the reserved bytes.
  const buf = buildDicom({
    transferSyntax: TS_EXPLICIT_LE,
    elements: [{ tag: "00181020", vr: "OB", value: Buffer.from([0x01, 0x02]) }],
  });
  // Locate the OB element header: scan for the VR bytes "OB" after File Meta.
  // File Meta is also Explicit-LE; the dataset OB is the LAST "OB" occurrence.
  const obIdx = buf.lastIndexOf(Buffer.from("OB", "ascii"));
  if (obIdx > 0 && obIdx + 3 < buf.length) {
    // Reserved bytes immediately follow the 2-byte VR.
    buf[obIdx + 2] = 0x00;
    buf[obIdx + 3] = 0xff; // non-zero → triggers the warning
  }
  return buf;
}

/**
 * Inputs that legitimately throw a Tier-3 fatal (the only sanctioned throws).
 * The lenient runner accepts these via its `isFatal` predicate.
 */
function fatalInput(): fc.Arbitrary<Buffer> {
  const empty = fc.constant(Buffer.alloc(0));
  const notDicom = fc
    .string({ minLength: 16, maxLength: 64 })
    .map((s) => Buffer.from(`NOTDICOM-${s}`, "ascii"));
  const missingTsUid = fc.constant(
    buildDicom({ transferSyntax: TS_EXPLICIT_LE, elements: [], skipTransferSyntaxUID: true }),
  );
  const unsupportedTs = fc.constant(
    buildDicom({ transferSyntax: "1.2.840.10008.1.2.4.50", elements: [] }),
  );
  return fc.oneof(empty, notDicom, missingTsUid, unsupportedTs);
}

/**
 * The union of every lenient-mode input shape: recoverable deviations,
 * sanctioned fatals, plus arbitrary bytes and truncations folded in so the
 * lenient invariant also sees pure garbage. Weighted toward recoverable
 * fixtures so the warning-well-formedness assertions get heavy exercise.
 */
export function recoverableInput(): fc.Arbitrary<Buffer> {
  return fc.oneof(
    { weight: 5, arbitrary: recoverableFixture() },
    { weight: 2, arbitrary: fatalInput() },
    { weight: 2, arbitrary: truncatedValidFile() },
    { weight: 1, arbitrary: arbitraryBytes() },
  );
}

// ---------------------------------------------------------------------------
// Hostile bytes (fuzz invariant).
// ---------------------------------------------------------------------------

/**
 * Arbitrary random byte buffers, 0–512 bytes. The most hostile input: no
 * structure at all. The parser must throw only a sanctioned `DicomParseError`,
 * never a `RangeError`/`TypeError`, never hang, never OOM.
 */
export function arbitraryBytes(): fc.Arbitrary<Buffer> {
  return fc.uint8Array({ minLength: 0, maxLength: 512 }).map((a) => Buffer.from(a));
}

/**
 * Random byte buffers biased toward DICOM-shaped structure: a real preamble +
 * `DICM` magic followed by arbitrary bytes, so the parser gets PAST the Part 10
 * framing check and then fuzzes the File Meta / dataset parsers with garbage.
 * This reaches deeper code paths than pure noise.
 */
export function dicomShapedGarbage(): fc.Arbitrary<Buffer> {
  return fc.uint8Array({ minLength: 0, maxLength: 400 }).map((a) => {
    const preamble = Buffer.alloc(128, 0x00);
    const magic = Buffer.from("DICM", "ascii");
    return Buffer.concat([preamble, magic, Buffer.from(a)]);
  });
}

/**
 * A random truncation of a well-formed multi-element file. Builds a valid buffer
 * across all four transfer syntaxes (including the numeric/SQ-bearing cases the
 * round-trip generator excludes) then cuts it at a random offset — the classic
 * "partial file on disk / short read off the wire" shape. The parser must
 * recover or throw a sanctioned fatal; never crash unexpectedly.
 */
export function truncatedValidFile(): fc.Arbitrary<Buffer> {
  const richElements: BuildDicomOptions["elements"] = [
    { tag: "00100010", vr: "PN", value: Buffer.from("DOE^JANE", "ascii") },
    { tag: "00280010", vr: "US", value: Buffer.from([0x00, 0x02]) },
    { tag: "00080060", vr: "CS", value: Buffer.from("CT", "ascii") },
    {
      tag: "0040A730",
      undefinedLength: true,
      items: [{ elements: [{ tag: "00080100", vr: "SH", value: Buffer.from("CODE", "ascii") }] }],
    },
  ];
  return fc
    .record({
      ts: fc.constantFrom<string[]>(...ALL_V1_TS),
      cut: fc.double({ min: 0, max: 1, noNaN: true }),
    })
    .map(({ ts, cut }) => {
      const full = buildDicom({ transferSyntax: ts, elements: richElements });
      const end = Math.max(0, Math.floor(full.length * cut));
      return full.subarray(0, end);
    });
}

/**
 * The union fuzz generator: pure noise, DICOM-shaped garbage, and truncations
 * of valid files. This is what the fuzz invariant feeds the parser.
 */
export function fuzzInput(): fc.Arbitrary<Buffer> {
  return fc.oneof(
    { weight: 2, arbitrary: arbitraryBytes() },
    { weight: 2, arbitrary: dicomShapedGarbage() },
    { weight: 3, arbitrary: truncatedValidFile() },
  );
}
